//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interation.iRepeater.Repository.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class iRepeaterDbContext : DbContext
    {
        public iRepeaterDbContext()
            : base("name=iRepeaterDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

        }
    
        public DbSet<Product> Product { get; set; }
        public DbSet<Topic> Topic { get; set; }
        public DbSet<TopicGroup> TopicGroup { get; set; }
        public DbSet<TopicGroupMemberMapping> TopicGroupMemberMapping { get; set; }
    
        public virtual ObjectResult<Topic> Proc_SelectCurrentTopics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Topic>("Proc_SelectCurrentTopics");
        }
    
        public virtual ObjectResult<Topic> Proc_SelectCurrentTopics(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Topic>("Proc_SelectCurrentTopics", mergeOption);
        }
    
        public virtual ObjectResult<Product> Proc_SelectHottestProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("Proc_SelectHottestProducts");
        }
    
        public virtual ObjectResult<Product> Proc_SelectHottestProducts(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("Proc_SelectHottestProducts", mergeOption);
        }
    
        public virtual ObjectResult<Product> Proc_SelectNewestProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("Proc_SelectNewestProducts");
        }
    
        public virtual ObjectResult<Product> Proc_SelectNewestProducts(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("Proc_SelectNewestProducts", mergeOption);
        }
    }
}
